version: '3.8'

services:
  rust-app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5433/kibe_db
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kibe_db
    ports:
      - "5433:5433"